#!/bin/bash

echo "Setting up...";
rm -rf ./nodejs-assets/nodejs-project;
mkdir -p ./nodejs-assets/nodejs-project;
if [ -f ./nodejs-assets/BUILD_NATIVE_MODULES.txt ]
then
  echo "Build Native Modules on";
else
  echo '1' >./nodejs-assets/BUILD_NATIVE_MODULES.txt;
  echo "Set Build Native Modules on";
fi
cp -r ./src/nodejs-project ./nodejs-assets;
cp ./src/nodejs-project/package.json ./nodejs-assets/nodejs-project;

echo "Installing dependencies...";
cd ./nodejs-assets/nodejs-project && npm i && cd ../..;

echo "Done.";
